#dev only

version: '3.8'
services:
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/tbf/db
  app:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      MONGODB_URI: mongodb://mongo:27017/
    volumes:
      - tbfab_data_container:/tbf/app

volumes:
  mongodb_data_container:
  tbfab_data_container: